### ISSUE TITLE
Translation dependency not indicated

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/component-subscription-status#12]
It looks like this has a dependency on widget.common.translate.  Not sure where that resides.

**Comment by ByronDarlison** [comment]
@tejohnso @alex-deaconu can you confirm if this issue is still open and if it is, I am assuming that it needs to be corrected as part of storage enhancements, is that right? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison @tejohnso this is not relevant anymore. We have changed the way we store translation files, and have a repository specifically made for it, which prevents these types of issues. Closing. Thanks.

**Comment by ByronDarlison** [comment]
Thanks
