### ISSUE TITLE
No call to action for the status of "Not Subscribed"

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/component-subscription-status#31]
For a product that does not have a trail available the status shows "Not Subscribed". http://www.screencast.com/t/kuJfBOvGb

The status should show "Not Subscribed **Subscribe**" where Subscribe is the call to action that when selected opens the in app Store on the applicable product.

**Comment by alex-deaconu** [comment]
@alanclayton sorry I don't follow. Wasn't @fjvallarino working on this PR? Why are all these issues assigned to me? Thanks.

**Comment by alanclayton** [comment]
@fjvallarino can you please take a look at this issue.

**Comment by alanclayton** [comment]
Verified
