### ISSUE TITLE
Widget settings show incorrect days until trial expired.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/component-subscription-status#37]
Widget settings is showing 30 days until trial expired - http://www.screencast.com/t/oleozSue

Store shows 29 days until trial expired - http://www.screencast.com/t/kwRINzCdq

FYI @alex-deaconu

**Comment by alex-deaconu** [comment]
@btfrise this issue should now be fixed. You can verify via the Financial Table widget. Thanks.

**Comment by btfrise** [comment]
Verified. Closing.
